[package]
name = "cache_streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
bytes = "1.8"
chrono = "0.4"
futures = "0.3"
headers = "0.4"
hex = "0.4"
intrusive-collections = "0.9"
intrusive-lru-cache = { version = "0.1", default-features = false }
parking_lot = "0.12"
reqwest = { version = "0.12", features = ["stream"] }
ring = "0.16"
tokio = { version = "1", features = ["full"] }
url = "2.3"
